export enum TestStatus {
    PENDING = 'PENDING',
    COLLECTION_PENDING = 'COLLECTION_PENDING',
    COLLECTED = 'COLLECTED',
    PROCESSING = 'PROCESSING',
    COMPLETED = 'COMPLETED',
    CANCELLED = 'CANCELLED'
} 